admin/config/routes.rb
Rails.application.routes.draw do
  resources :travels
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  resources :users
  get 'home',to: 'page#index'
  root 'sessions#new'

  resources :schedules

end

admin/app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

admin/app/models/travel.rb
class Travel < ActiveRecord::Base
	mount_uploader :image, ImageUploader
	validates_processing_of :image
	validate :image_size_validation
	 
	private
	  def image_size_validation
	    errors[:image] << "Anh phai lon hon 200Kb" if image.size < 0.02.megabytes
	  end
end

admin/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

admin/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def current_user
    User.where(id: session[:user_id]).first
  end
  helper_method :current_user
end

admin/app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  	if !current_user
  		redirect_to root_path 
  	end
  end
end

admin/app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    if !current_user
      redirect_to root_path 
    else
      @schedules = Schedule.paginate(:page => params[:page], :per_page => 8).order('id DESC')
    end
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
    if !current_user
      redirect_to root_path 
    end
  end

  # GET /schedules/new
  def new
    if !current_user
      redirect_to root_path 
    else
      @schedule = Schedule.new
    end
  end

  # GET /schedules/1/edit
  def edit
    if !current_user
      redirect_to root_path 
    end
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      params.require(:schedule).permit(:startdate, :enddate, :startplace, :endplace)
    end
end

admin/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
		if current_user
  			redirect_to home_path 
  		end
	end
	def create
		user = User.find_by(username: params[:username])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to home_path, notice: 'Logged in!'
		else
			render :new
		end
	end
	def destroy
		session[:user_id] = nil
		redirect_to root_url, notice: 'Logged out!'
	end
end

admin/app/controllers/travels_controller.rb
class TravelsController < ApplicationController
  before_action :set_travel, only: [:show, :edit, :update, :destroy]

  # GET /travels
  # GET /travels.json
  def index
    if !current_user
      redirect_to root_path 
    else
      @travels = Travel.paginate(:page => params[:page], :per_page => 8).order('id DESC')
    end
  end

  # GET /travels/1
  # GET /travels/1.json
  def show
    if !current_user
      redirect_to root_path 
    end
  end

  # GET /travels/new
  def new
    if !current_user
      redirect_to root_path 
    else
      @travel = Travel.new
    end
  end

  # GET /travels/1/edit
  def edit
    if !current_user
      redirect_to root_path 
    end
  end

  # POST /travels
  # POST /travels.json
  def create
    if !current_user
      redirect_to root_path 
    else
      @travel = Travel.new(travel_params)

      respond_to do |format|
        if @travel.save
          format.html { redirect_to @travel, notice: 'Travel was successfully created.' }
          format.json { render :show, status: :created, location: @travel }
        else
          format.html { render :new }
          format.json { render json: @travel.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /travels/1
  # PATCH/PUT /travels/1.json
  def update
    respond_to do |format|
      if @travel.update(travel_params)
        format.html { redirect_to @travel, notice: 'Travel was successfully updated.' }
        format.json { render :show, status: :ok, location: @travel }
      else
        format.html { render :edit }
        format.json { render json: @travel.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /travels/1
  # DELETE /travels/1.json
  def destroy
    @travel.destroy
    respond_to do |format|
      format.html { redirect_to travels_url, notice: 'Travel was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_travel
      @travel = Travel.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def travel_params
      params.require(:travel).permit(:title, :idtype, :image)
    end
end

admin/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    if !current_user
      redirect_to root_path 
    else
      @users = User.all
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    if !current_user
      redirect_to root_path 
    end
  end

  # GET /users/new
  def new
    if !current_user
      redirect_to root_path 
    else
      @user = User.new
    end
  end

  # GET /users/1/edit
  def edit
    if !current_user
      redirect_to root_path 
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end
end

admin/app/helpers/application_helper.rb
module ApplicationHelper
end

admin/app/helpers/page_helper.rb
module PageHelper
end

admin/app/helpers/schedules_helper.rb
module SchedulesHelper
end

admin/app/helpers/sessions_helper.rb
module SessionsHelper
   
end

admin/app/helpers/travels_helper.rb
module TravelsHelper
end

admin/app/helpers/users_helper.rb
module UsersHelper
end

admin/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Admin</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	

	<!--<div class="container-fluid">
		<main>	
	-->
	<div id="wrapper">
			<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
				<div class="navbar-header">
	                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
	                    <span class="sr-only">Toggle navigation</span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                    <span class="icon-bar"></span>
	                </button>
	                <%= link_to "DLPN Admin", home_path, class: "navbar-brand" %>
	            </div>
	            <ul class="nav navbar-top-links navbar-right">
	            	<li class="dropdown">
	                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
	                        <i class="glyphicon glyphicon-user"></i> <i class="glyphicon glyphicon-triangle-bottom"></i>
	                    </a>
	                    <% if current_user %> 
		                    <ul class="dropdown-menu dropdown-user">
		                    	 	
			                    <li><a href=""><i class="glyphicon glyphicon-user fa-fw"></i> <%= current_user.username %></a>
			                        </li>
			                        <li><a href=""><i class=" glyphicon glyphicon-cog"></i> Cài đặt</a>
			                        </li>
			                        <li class="divider"></li>
			                        <li>
			                        <%= link_to(logout_path) do %>
			                        	<i class="glyphicon glyphicon-log-out"></i>
			                        	Đăng xuất
			                        <%end%>
		                        </li>
		                        
		                    </ul>
	                    <% end %>
	                    <!-- /.dropdown-user -->
	                </li>
	            </ul>
	            <div class="navbar-default sidebar" role="navigation">
	                <div class="sidebar-nav navbar-collapse">
	                    <ul class="nav" id="side-menu">
	                        <li class="sidebar-search">
	                            <div class="input-group custom-search-form">
	                                <input type="text" class="form-control" placeholder="Search...">
	                                <span class="input-group-btn">
	                                    <button class="btn btn-default" type="button">
	                                        <i class="glyphicon glyphicon-search"></i>
	                                    </button>
	                                </span>
	                            </div>
	                            <!-- /input-group -->
	                        </li>
	                        <li>
	                            <%= link_to(home_path) do %>
		                            <i class="glyphicon glyphicon-stats glyphicon-fw"></i> 
		                            Thống kê
		                        </a>
		                        <%end%>
	                        </li>
	                        <li>
	                            <a href="#">
	                            	<i class="glyphicon glyphicon-calendar"></i> 
	                            	Lịch trình
	                            </a>
	                            <ul class="nav nav-second-level">
	                                <li>
	                                	<%= link_to 'Bảng lịch trình', schedules_path %>
	                                 
	                                </li>
	                                <li>
	                                	<%= link_to 'Thêm lịch trình', new_schedule_path %>
	                                </li>
	                            </ul>
	                            <!-- /.nav-second-level -->
	                        </li>
	                        <li>
	                            <a href="#">
	                            	<i class="glyphicon glyphicon-picture"></i> 
	                            	Ảnh
	                            </a>
	                            <ul class="nav nav-second-level">
	                                <li>
	                                	<%= link_to 'Thông tin ảnh', travels_path %>
	                                </li>
	                                <li>
	                                	<%= link_to 'Thêm ảnh', new_travel_path %>
	                                </li>
	                            </ul>
	                            <!-- /.nav-second-level -->
	                        </li>
	                    </ul>
                    </div>
                </div>


				
			</nav>
			<div id="page-wrapper" data-role=”page”>
	            <%= yield %>                    
	        </div>			
			
		<!--</main>-->
	</div>
</body>
</html>

admin/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

admin/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

admin/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

admin/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

admin/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>