adminpage/config/routes.rb
Rails.application.routes.draw do
  resources :session, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'session#new', as: 'login'
  post   'login',   to: 'session#create'
  delete 'logout',  to: 'session#destroy', as: 'logout'
  resources :users
  get 'page/index'
  root 'page#index'

end

adminpage/app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :password
	validates :uname, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
	validates :password, :confirmation => true #password_confirmation attr
	validates_length_of :password, :in => 6..20, :on => :create
end

adminpage/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def current_user
    User.where(id: session[:user_id]).first
  end
  helper_method :current_user
end

adminpage/app/controllers/page_controller.rb
class PageController < ApplicationController
  def index
  end
end

adminpage/app/controllers/session_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
	user = User.where(:uname => params[:session][:uname].downcase).first
	if user && user.authenticate(params[:session][:password])
		# Log the user in and redirect to the user's show page.
		log_in user
		redirect_to user

	else
	# Create an error message.
		flash.now[:danger] = 'Invalid username/password combination'
		render 'new'
	end
  end

  def destroy
  end
end

adminpage/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:uname, :password)
    end
end

adminpage/app/helpers/application_helper.rb
module ApplicationHelper
end

adminpage/app/helpers/page_helper.rb
module PageHelper
end

adminpage/app/helpers/session_helper.rb
module SessionHelper
	def log_in(user)
    	session[:user_id] = user.id
	end
end

adminpage/app/helpers/users_helper.rb
module UsersHelper
end

adminpage/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Adminpage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

adminpage/app/views/page/index.html.erb
<div id="user_header">
<% if current_user %>
Logged in as <%= current_user.uname %>.
<%= link_to "Log Out", logout_path %>
<% else %>
<%= link_to "Sign Up", signup_path %> or
<%= link_to "Log In", login_path %>
<% end %>
</div>
<% flash.each do |key, value| %>
<%= content_tag(:div, class: "alert alert-#{key}") do %>
<p><%= value %></p>
<% end %>
<% end %>

adminpage/app/views/session/create.html.erb
<h1>Session#create</h1>
<p>Find me in app/views/session/create.html.erb</p>

adminpage/app/views/session/destroy.html.erb
<h1>Session#destroy</h1>
<p>Find me in app/views/session/destroy.html.erb</p>

adminpage/app/views/session/new.html.erb
<% provide(:title, "Log in") %>
<h1>Log in</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(:session, url: login_path) do |f| %>

      <%= f.label :uname %>
      <%= f.text_field :uname, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.submit "Log in", class: "btn btn-primary" %>
    <% end %>

    <p>New user? <%= link_to "Sign up now!", signup_path %></p>
  </div>
</div>

adminpage/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
      <%= f.label :uname %>
      <%= f.text_field :uname %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
<% end %>

adminpage/app/views/users/edit.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    	<%= render 'form' %>


		<%= link_to 'Show', @user %> |
		<%= link_to 'Back', users_path %>
  </div>
</div>

adminpage/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Uname</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.uname %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

adminpage/app/views/users/new.html.erb
<h1>New User</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    	<%= render 'form' %>

		<%= link_to 'Back', users_path %>

    	
  </div>
</div>

adminpage/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Uname:</strong>
  <%= @user.uname %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>